spring.application.name=ms-reservas

server.port=8084

spring.datasource.url=jdbc:h2:file:C:/Users/pazoy/Music/Proyecto Marfuego/data/reservasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true

ms.locales.url=${MS_LOCALES_URI:http://localhost:8081}