spring.application.name=ms-locales

server.port=8081

spring.datasource.url=jdbc:h2:file:C:/Users/pazoy/Music/Proyecto Marfuego/data/localesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true